name: Build SkipCash APK

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Set up Java
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.19.x'
        channel: 'stable'

    - name: Initialize Skeleton & Copy Files
      run: |
        flutter create --org com.jamal.skipcash temp_app
        cp main.dart temp_app/lib/main.dart
        cp pubspec.yaml temp_app/pubspec.yaml
        cd temp_app
        flutter pub get

    - name: Build APK
      run: |
        cd temp_app
        flutter build apk --release

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: SkipCash-App
        path: temp_app/build/app/outputs/flutter-apk/app-release.apk
